<a href="https://colab.research.google.com/github/kittikhun62/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #package สำฟรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบเมทริกซ์)

In [2]:
import numpy as np #package สำฟรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบเมทริกซ์)

### Numpy Array

#### สร้าง numpy array

In [3]:
np_a = np.array([[1,2,3],[4,5,6]])

In [4]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np_a.shape

(2, 3)

In [6]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

#### matrix transpose

In [7]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### สร้าง matrix เริ่มต้น (zeros,ones)

In [8]:
np_z = np.zeros((4,5))  
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

### สร้าง matrix random ค่าเเบบมั่ว ๆ

In [11]:
np.random.randn(5,5) # randn คือ random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[ 0.10043203,  1.75649377, -0.22283961,  0.51618007,  1.55923395],
       [ 0.22592143,  0.20215894,  0.26337685,  0.85532297,  0.95255522],
       [ 0.07956651,  0.46689719,  1.5100838 , -0.69550822,  1.83577693],
       [-1.96547568,  0.01657988,  0.78004644, -0.81773011,  0.99803323],
       [-1.08883255, -0.44926516, -0.2079144 ,  1.02068439,  0.31181677]])

In [12]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ 1.29821413, -5.42671049,  5.15508625],
       [-1.13053361, -6.08564952,  5.82928396],
       [ 4.01411871,  8.74040921,  5.56660363]])

In [13]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[ 9,  6,  6,  6,  6],
       [ 7,  6, 10,  7,  6],
       [10,  6, 10,  5,  9],
       [ 9,  9, 10,  5, 10]])

In [14]:
import numpy as np #package สำฟรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบเมทริกซ์)

### Numpy Array

#### สร้าง numpy array

In [15]:
np_a = np.array([[1,2,3],[4,5,6]])

In [16]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np_a.shape

(2, 3)

In [18]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

#### matrix transpose

### สร้าง matrix เริ่มต้น (zeros,ones)

In [20]:
np_z = np.zeros((4,5))  
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

### สร้าง matrix random ค่าเเบบมั่ว ๆ

In [23]:
np.random.randn(5,5) # randn คือ random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.6702103 , -0.25864182, -0.06839167, -0.17113043,  2.12367557],
       [-0.51155766, -2.03531226,  0.88734095,  0.16085243, -0.29390499],
       [ 0.73021079,  0.90710417,  0.3549102 ,  0.43761823, -0.21123048],
       [-0.7800118 ,  0.29398133, -1.21050398, -0.63167004, -1.12857671],
       [-0.87030617,  2.37023163,  0.20651381,  0.04339808,  0.03986339]])

In [24]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ 6.11233964,  8.76857342, 12.298761  ],
       [-1.67947218, -1.36321857,  4.41372559],
       [11.55227933,  3.9450026 ,  0.69581529]])

In [25]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[ 9,  6,  5,  5,  8],
       [ 6,  5,  6,  5, 10],
       [ 9,  7,  7,  5,  7],
       [10,  6,  7, 10,  6]])

### Numpy Array

#### สร้าง numpy array

In [26]:
np_a = np.array([[1,2,3],[4,5,6]])

In [27]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np_a.shape

(2, 3)

In [29]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### สร้าง matrix เริ่มต้น (zeros,ones)

In [31]:
np_z = np.zeros((4,5))  
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

### สร้าง matrix random ค่าเเบบมั่ว ๆ

In [34]:
np.random.randn(5,5) # randn คือ random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.57134641, -1.46083246, -1.45167459, -0.0546088 , -0.65790473],
       [ 0.84554379, -0.4542728 , -0.21370754,  1.33202398,  0.27907908],
       [-0.43781946, -1.30729522, -0.07661953, -0.67989086,  1.63361428],
       [ 0.90084042,  0.74361932,  2.17592459,  0.72513873,  0.51049785],
       [ 0.25830168,  0.25011036,  0.40136525,  0.85505433,  0.53676066]])

In [35]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[-10.05350336,  -6.69062224,   0.37179752],
       [ -0.32351938,  -1.01200947,   8.90970835],
       [ -0.30719126,   4.59821793,   5.49178711]])

In [36]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ค่าตั้งเเต่ระหว่าง 5 ถึง 10 (5,11,(ขนาด 4x5))

array([[ 9, 10,  5, 10,  5],
       [ 6,  8, 10,  9,  9],
       [ 8,  7,  5,  8,  6],
       [10,  8,  9,  7, 10]])

#### matrix transpose

In [37]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
np_a.T #transpose สลับเเถวเป็ฯหลักสลับหลักเป็นเเถว

array([[1, 4],
       [2, 5],
       [3, 6]])

In [38]:
1+np_a # add scalar to matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [41]:
2 * np_a # maltiply scalar to matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
np_a.T + np_b

array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

In [44]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [46]:
np_a + np_c #adding martrix to martrix

array([[7, 7, 7],
       [7, 7, 7]])

In [47]:
np_c.shape

(2, 3)

In [48]:
np_a.shape

(2, 3)

In [50]:
np_c.T.shape

(3, 2)

In [49]:
np.dot(np_a,np_c.T) # mutpotling martrix to martrix (a,b) X (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

### Indexing & Slicing


In [51]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np_a[1,1]

5

In [56]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

In [58]:
np_a[0,:]


array([1, 2, 3])

## useful  functions

In [60]:
np.sum(np_a)

21

In [61]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.sum(np_a,axis=0) #axis 0 คือให้มันsumในเเกนไหน หรือรวมเลขในเเต่ละเเถว

array([5, 7, 9])

In [67]:
np.sum(np_a,axis=1) #axis 0 หรือรวมเลขในเเต่ละหลัก

array([ 6, 15])

In [65]:
np.mean(np_a)

3.5

In [66]:
np.mean(np_a,axis=0) #หา mean ของคอมลัม

array([2.5, 3.5, 4.5])

## วนลูปเอง


'''
 1.จัดฟังก์ชันไม่ได้
 2.ทำให้มันดูพิเศษ

summation

In [71]:
sum_all = 0

for  row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all = sum_all + np_a[row,col]
        print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]} sum_all={sum_all}')
    print(sum_all)

we are at row=0,col=0 np_a[0,0]=1 sum_all=1
we are at row=0,col=1 np_a[0,1]=2 sum_all=3
we are at row=0,col=2 np_a[0,2]=3 sum_all=6
6
we are at row=1,col=0 np_a[1,0]=4 sum_all=10
we are at row=1,col=1 np_a[1,1]=5 sum_all=15
we are at row=1,col=2 np_a[1,2]=6 sum_all=21
21


np.sum(np_a,axis = 0)

In [72]:
sum_all = np.zeros(np_a.shape[1])

for  row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


Quiz กลุ่ม

วนลูปหาค่า

* ```np.sum(np_a,axis=1)``` sukuna /
* ```np.mean(np_a)``` i love อ.ต้น /
* ```np.mean(np_a,axis=0)``` natashar /
* ```np.mean(np_a,axis=1)``` teletubby /
* ```np.max(np_a)``` numba one /
* ```np.max(np_a,axis=0)``` เอกาไร้สติ /
* ```np.max(np_a,axis=1)``` sandbox /
* ```np.min(np_a)``` ลูกหมี /
* ```np.min(np_a,axis=0)``` wakame /
* ```np.min(np_a,axis=1)``` แมวส้ม /

In [132]:
# np.max(np_a,axis=1)
max_all = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
    max_all[row] = max(np_a[row,:])
print(max_all)

[3. 6.]


In [133]:
#np.mean(np_a,axis=0)
mean_all = np.zeros(np_a.shape[1])
for row in range(np_a.shape[0]):
     for col in range(np_a.shape[1]):
          mean_all[col] = mean_all[col] + np_a[row,col]/np_a.shape[0]
print(mean_all)

[2.5 3.5 4.5]


In [134]:
#np.mean(np_a,axis=1)
sum_all = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]): 
        sum_all[row] = sum_all[row] + np_a[row,col]
sum_all = sum_all/np_a.shape[1]
print(sum_all)

[2. 5.]


In [135]:
#np.max(np_a)
max_a = -100000000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] > max_a :
            max_a = np_a[row,col]
print(max_a)

6


In [136]:
### 10. np.min(np_a,axis=1)
min_row = np.zeros(np_a.shape[0])
for row in range(np_a.shape[0]):
   min_row[row] = min(np_a[row,:])
print(min_row)

[1. 4.]


In [137]:
# np.min(np_a,axis=0)
min_all = np.zeros(np_a.shape[1])

for col in range(np_a.shape[1]):
    min_all[col] = min(np_a[:,col])
print(min_all)

[1. 2. 3.]


In [138]:
# np.min(np_a)  ลูกหมี
minV = 100000
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        if np_a[row,col] < minV:
            minV = np_a[row,col]
print(minV)


1


In [139]:
# np.max(np_a,axis=0)
max_all = -100000 * np.ones(np_a.shape[1])
for col in range(np_a.shape[1]):
    for row in range(np_a.shape[0]):
        if np_a[row,col] > max_all[col]: 
            max_all[col] = np_a[row,col]
print(max_all)

[4. 5. 6.]


In [140]:
#np.mean(np_a)
mean_all = 0
for row in range(np_a.shape[0]):
    for col in range(np_a.shape[1]):
        mean_all = mean_all + np_a[row,col]
mean_all = mean_all/(np_a.shape[0]*np_a.shape[1])
print(mean_all)

3.5
